import mongoose from 'mongoose'

const customerSchema = new mongoose.Schema(
  {
    // A single object contains data returned from 3rd party API
    customerData: { type: Object },
    ID: { type: String },
    Name: { type: String },
    Description: { type: String },
    Website: { type: String },
    IsActive: { type: String },
    InActiveReason: { type: String },
    PrimaryUserID: { type: String },
    PrimaryContact: { type: String },
    DateCreated: { type: String },
    DateModified: { type: String },
    CreatorID: { type: String },
    ModifierID: { type: String },
    HasPortalAccess: { type: String },
    CreatedBy: { type: String },
    LastModifiedBy: { type: String },
    SAExpirationDate: { type: String },
    SlaName: { type: String },
    CRMLinkID: { type: String },
    SlaLevelID: { type: String },
    DefaultWikiArticleID: { type: String },
    DefaultSupportGroupID: { type: String },
    DefaultSupportGroup: { type: String },
    DefaultSupportUserID: { type: String },
    DefaultSupportUser: { type: String },
    Domains: { type: String },
    SupportHours: { type: String },
    SupportHoursUsed: { type: String },
    SupportHoursRemaining: { type: String },
    NeedsIndexing: { type: String },
    CustDisIndex: { type: String },
    CustDistIndexTrend: { type: String },
    EmailTicketActions: { type: String },
    EntityID: { type: String },
    AccountManager: { type: String },
    AMIMeters: { type: String },
    AssetManagementSystem: { type: String },
    Backflow: { type: String },
    BillPrintVendor: { type: String },
    BillingFrequency: { type: String },
    CISProdBuild: { type: String },
    ClientSince: { type: String },
    ClientStatus: { type: String },
    CustomerPortal: { type: String },
    Database: { type: String },
    Electric: { type: String },
    FinancialSystemIntegration: { type: String },
    Gas: { type: String },
    GIS: { type: String },
    IncumbentProduct: { type: String },
    IVRVendor: { type: String },
    Kiosk: { type: String },
    LinkProdBuild: { type: String },
    MeterDataManagement: { type: String },
    MeterReadingSystem: { type: String },
    MobileProdBuild: { type: String },
    Customers: { type: String },
    NumberofActiveMeters: { type: String },
    NumberofLicensedUsers: { type: String },
    OriginalGoLIveDate: { type: String },
    OtherServices: { type: String },
    OtherVendors: { type: String },
    PaymentProcessor: { type: String },
    ProjectManager: { type: String },
    PSAppCon: { type: String },
    PSTech: { type: String },
    RESTAPIEnabled: { type: String },
    RESTInterfaces: { type: String },
    Sewer: { type: String },
    Interfaces: { type: String },
    SolidWaste: { type: String },
    Storm: { type: String },
    TeamLead: { type: String },
    UsesNetMetering: { type: String },
    GoLiveDate: { type: String },
    TransitiontoSupportDate: { type: String },
    WasterWater: { type: String },
    Water: { type: String },
    WorkflowManagementSystem: { type: String }
  },
  { collection: 'customers', timestamps: true } // documents include createdAt and updatedAt
)

export default mongoose.model('Customer', customerSchema)
