import mongoose from 'mongoose'

const ticketSchema = new mongoose.Schema(
  {
    // A single object contains data returned from 3rd party API
    ticketData: { type: Object },

    ID: { type: Object },
    ProductName: { type: Object },
    ReportedVersion: { type: Object },
    SolvedVersion: { type: Object },
    GroupName: { type: Object },
    TicketTypeName: { type: Object },
    UserName: { type: Object },
    Status: { type: Object },
    StatusPosition: { type: Object },
    SeverityPosition: { type: Object },
    IsClosed: { type: Object },
    Severity: { type: Object },
    TicketNumber: { type: Object },
    IsVisibleOnPortal: { type: Object },
    IsKnowledgeBase: { type: Object },
    ReportedVersionID: { type: Object },
    SolvedVersionID: { type: Object },
    ProductID: { type: Object },
    GroupID: { type: Object },
    UserID: { type: Object },
    TicketStatusID: { type: Object },
    TicketTypeID: { type: Object },
    TicketSeverityID: { type: Object },
    OrganizationID: { type: Object },
    Name: { type: Object },
    ParentID: { type: Object },
    ModifierID: { type: Object },
    CreatorID: { type: Object },
    DateModified: { type: Object },
    DateCreated: { type: Object },
    DateClosed: { type: Object },
    CloserID: { type: Object },
    DaysClosed: { type: Object },
    DaysOpened: { type: Object },
    CloserName: { type: Object },
    CreatorName: { type: Object },
    ModifierName: { type: Object },
    HoursSpent: { type: Object },
    SlaViolationTime: { type: Object },
    SlaWarningTime: { type: Object },
    SlaViolationHours: { type: Object },
    SlaWarningHours: { type: Object },
    KnowledgeBaseCategoryID: { type: Object },
    KnowledgeBaseCategoryName: { type: Object },
    DueDate: { type: Object },
    PrimaryCustomer: { type: Object },
    TicketSource: { type: Object },
    JiraKey: { type: Object },
    IsSecured: { type: Object },
    Customers: { type: Object },
    Contacts: { type: Object },
    BWPBuild: { type: Object },
    BWPModule: { type: Object },
    cGroup: { type: Object },
    CISV3BuildNo: { type: Object },
    CISV3Module: { type: Object },
    CISV4BuildNo: { type: Object },
    CISV4Module: { type: Object },
    CISV5Build: { type: Object },
    CISV5Module: { type: Object },
    CurrentRelease: { type: Object },
    FISModule: { type: Object },
    LinkV3BuildNo: { type: Object },
    LinkV3IssueModule: { type: Object },
    LinkV4BuildNo: { type: Object },
    LinkV4IssueModule: { type: Object },
    MobileV3BuildNo: { type: Object },
    MobileV3IssueModule: { type: Object },
    reopen: { type: Object },
    V3SpotBuildNo: { type: Object },
    V4SpotBuildNo: { type: Object },
    WMSModule: { type: Object },
    Tags: { type: Object }
  },
  { collection: 'tickets', timestamps: true } // documents include createdAt and updatedAt
)

export default mongoose.model('Ticket', ticketSchema)
